### PR TITLE
small fix: log entries are evicted by FIFO, not LIFO

### PR DESCRIPTION
**Pull request by J4nsen**
LIFO is a stack. here, log entires are removed in FIFO manner.

### CODE REVIEW

**Comment by edsub** [comment]
@J4nsen Did you manage to compile your fork (incl Log fix) into a deployable firmware file?
I do not master programming n C and I am suffering from a bug that crashes/reboots the charger when the Log is opened/requested (currently on EVSE-WiFi 1.1.1 as available on https://www.smartwb.de/firmware-downloads/). So getting a working firmware would be great. Can you help me get that?

**Comment by J4nsen** [comment]
Hi edsub,

my change was purely cosmetic, so I didnt try to compile the firmware. :/ Sorry, cant help you there

**Comment by edsub** [comment]
Thx for response. Are you experiencing the software to crash when you access the log (via web gui or api)?
Because that is my issue. And frankly I cannot believe this has not been fixed if the issue is with all users (meaning: It can be just my setup / ESP setup causing this).

**Comment by J4nsen** [comment]
I can access the log without crashing the system. Perhaps you have a broken log entry which triggers the crash.

**Pull request closed without merging**
